site_name: Try GitHub Pages
site_url: https://arisay-vs.github.io/McDoksTest/
repo_name: ArisaY-vs/McDoksTest

theme:
  name: material
  palette:
    primary: pink
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

plugins:
  search:
    lang: 'ja'

nav:
  - 概要: index.md
  - 1999展: 1999.md
