site_name: MOGLA取扱説明書
repo_url: https://arisay-vs.github.io/SimulationPRJ.github.io/
repo_name: ArisaY-vs/SimulationPRJ.github.io # ドキュメントの構成
docs_dir: docs


nav:
  - 初期画面: index.md

# テーマの設定
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
  features:
    - navigation.top

plugins:
  search:
    lang: 'ja'

markdown_extensions:
  - admonition
  - pymdownx.details
  - footnotes